version: '3.8'

services:

  # DATADOG agent :: monitors what happens - https://app.datadoghq.com
  datadog:
    container_name: datadog
    platform: linux/amd64
    image: "datadog/agent:7.41.0"
    environment:
      - DD_API_KEY
      - DD_TAGS
      - DD_ENV
      - DD_APM_ENABLE=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION=true
#      - DD_AC_EXCLUDE=name:datadog
      - DD_LOG_LEVEL=error
    # expose:
    #   - 8126
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./datadog/run:/opt/datadog-agent/run:rw
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog", "service": "datadog"}]'
